catch BrokenPipeError in main
If you pipe the output of the linstor client trough some other program,
which does not fully read the input, we get this ugly backtrace:

```
linstor -m v l | true
Traceback (most recent call last):
  File "/usr/bin/linstor", line 24, in <module>
    linstor_client_main.main()
  File "/usr/lib/python3.9/site-packages/linstor_client_main.py", line 696, in main
    LinStorCLI().run()
  File "/usr/lib/python3.9/site-packages/linstor_client_main.py", line 661, in run
    rc = self.parse_and_execute(sys.argv[1:])
  File "/usr/lib/python3.9/site-packages/linstor_client_main.py", line 371, in parse_and_execute
    rc = args.func(args)
  File "/usr/lib/python3.9/site-packages/linstor_client/commands/vlm_cmds.py", line 349, in list_volumes
    return self.output_list(args, lstmsg, VolumeCommands.show_volumes)
  File "/usr/lib/python3.9/site-packages/linstor_client/commands/commands.py", line 425, in output_list
    cls._print_machine_readable(replies, args.output_version, machine_readable_raw)
  File "/usr/lib/python3.9/site-packages/linstor_client/commands/commands.py", line 492, in _print_machine_readable
    print(s)
BrokenPipeError: [Errno 32] Broken pipe
```

I added a specific try/except in _print_machine_readable.

But for the non-machine-readable output, I don't immediately see an obvious
place to specifically handle this exception.

So I also catche it in main().
But this may mask errors on file descriptors other than stdout,
which you may want to actually handle (instead of bailing out).
Your call.